Server/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
]

main/urls.py
""" Copyright (C) 2021 Patrick Frontzek
This file is part of OpenAssetTracker-Server.

OpenAssetTracker-Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenAssetTracker-Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenAssetTracker-Server.  If not, see <http://www.gnu.org/licenses/>.
"""

__author__ = "Patrick Frontzek"
__copyright__ = "Copyright 2021, Patrick Frontzek"
__license__ = "GPLv3"


from django.contrib.auth import views as auth_views
from django.templatetags.static import static
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

from . import api
from . import consumers
from . import views
from .auth_views import PasswordResetConfirmView

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("admincontrol", views.AdminControlView.as_view(), name="admincontrol"),
    path("echo", views.echoView.as_view()),
    path("map", views.MapView.as_view(), name="map"),
    path("manifest.webmanifest", views.WebManifestView.as_view(), name="webmanifest"),
    path("map/tabledata", views.TabledataView.as_view(), name="tabledata"),
    path("update", api.StatusView.as_view(), name="update"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("account/", include("main.auth_urls", namespace="auth")),
    path("update/statusses", views.UpdateStatuses.as_view()),
    path(
        "account/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="main/auth/password_reset.html", extra_context={"login": True}
        ),
        name="password_reset_confirm",
    ),
    path(
        "device/<int:imei>/export/<str:format>",
        views.ExportDevice.as_view(),
        name="device_export",
    ),
    path("device/", lambda r: views.HttpResponseBadRequest(), name="device_base"),
    path("debug", views.DebugView.as_view(), name="debug"),
    path("detail", views.DetailInfoView.as_view(), name="detail"),
    path("celltower/<int:stunden>", views.CelltowerView.as_view(), name="celltower"),
    path("update_bts", api.update_bts),
    path("tracker/", lambda r: views.HttpResponseBadRequest(), name="trackerData_base"),
    path("tracker/<int:imei>", views.TrackerDataView.as_view(), name="trackerData"),
    path(
        "favicon.ico",
        RedirectView.as_view(url=static("main/img/favicon.png")),
        name="favicon.ico",
    ),
]

websocket_urlpatterns = [
    path("ws/device/<int:imei>/", consumers.DeviceUpdateConsumer),
    path("ws/user/<int:user_id>/", consumers.UserUpdateConsumer),
]

main/forms.py
""" Copyright (C) 2021 Patrick Frontzek
This file is part of OpenAssetTracker-Server.

OpenAssetTracker-Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenAssetTracker-Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenAssetTracker-Server.  If not, see <http://www.gnu.org/licenses/>.
"""

__author__ = "Patrick Frontzek"
__copyright__ = "Copyright 2021, Patrick Frontzek"
__license__ = "GPLv3"

import json
from django.contrib.auth.models import User
from django.forms import CharField
from django.forms import EmailField
from django.forms import HiddenInput
from django.forms import ModelForm

from .models import Device


class UserCreationFormWithoutPassword(ModelForm):
    username = EmailField(label="Email")
    tracker = CharField(widget=HiddenInput())

    class Meta:
        model = User
        fields = ("username",)

    def save(self, commit=True) -> User:
        import string
        from random import SystemRandom

        user: User = super(ModelForm, self).save(commit=False)
        user.email = user.username
        user.set_password(
            "".join(SystemRandom().choices(string.ascii_letters + string.digits, k=128))
        )  # Zufälliges Passwort vergeben
        if commit:
            user.save()
        tracker = json.loads(self.cleaned_data["tracker"])
        for t in tracker:
            d: Device = Device.objects.get(sn=t)
            user.devices.add(d)
        if commit:
            user.save()
        return user


class TrackerSettingsForm(ModelForm):
    class Meta:
        model = Device
        fields = ("alias", "sleeptime", "sleeptime_unit")

main/views.py
""" Copyright (C) 2021 Patrick Frontzek
This file is part of OpenAssetTracker-Server.

OpenAssetTracker-Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenAssetTracker-Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenAssetTracker-Server.  If not, see <http://www.gnu.org/licenses/>.
"""

__author__ = "Patrick Frontzek"
__copyright__ = "Copyright 2021, Patrick Frontzek"
__license__ = "GPLv3"

import csv
import json
import math
from datetime import timedelta
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import F
from django.db.models import Q
from django.http import HttpRequest
from django.http import HttpResponseBadRequest
from django.http import HttpResponseForbidden
from django.http import JsonResponse
from django.shortcuts import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.base import View
from random import shuffle
from typing import List

from .forms import UserCreationFormWithoutPassword
from .models import Device
from .models import Measurement
from .models import Status
from .models import User


@method_decorator(csrf_exempt, "dispatch")
class echoView(View):
    def get(self, request):
        return HttpResponse("Hello World!")

    def post(self, request):
        print(request.POST)
        print(request.body)
        return HttpResponse(request.body)


class UpdateStatuses(View):
    def get(self, request: HttpRequest):
        from geopy.geocoders import Nominatim

        geolocator = Nominatim(user_agent="open_asset_tracker_webserver")
        for s in Status.objects.filter(city=None):
            s.set_city(geolocator)
            import time

            time.sleep(1)
        return HttpResponse("OK")


@method_decorator(login_required, "dispatch")
class MapView(View):
    def get(self, request: HttpRequest) -> str:
        context = {"title": "OpenAssetTracker"}
        if request.session.get("debug"):
            context["debug"] = True
            context["title"] = "OpenAssetTracker | Debug"
        return render(request=request, template_name="main/map.html", context=context)
        # return HttpResponse("\n".join([f"{d}: {d.last_position}" for d in Device.objects.all()]), status=200)


@method_decorator(login_required, "dispatch")
class DebugView(View):
    def get(self, request: HttpRequest):
        if request.session.get("debug"):
            del request.session["debug"]
        else:
            request.session["debug"] = True
        return redirect("index")


class DetailInfoView(View):
    def post(self, request: HttpRequest):
        if request.POST["type"] == "status":
            status = Status.objects.get(id=request.POST["id"])
            response = {"lat": status.lat, "lon": status.lon, "radius": status.radius}

            if request.session.get("debug"):
                measurements: List[Measurement] = status.cleaned_measurements
                response["cells"] = [
                    {
                        "lat": m.celltower.lat,
                        "lon": m.celltower.lon,
                        "radius": m.distance.meters,
                    }
                    for m in measurements
                ]
            return JsonResponse(response)

        return HttpResponseBadRequest()


@method_decorator(login_required, "dispatch")
class TabledataView(View):
    def post(self, request: HttpRequest):
        data = json.loads(request.body)
        response = {
            "draw": int(data["draw"]),
            "data": [],
            "recordsTotal": 0,
            "recordsFiltered": 0,
            "error": None,
        }

        if data["type"] == "status":
            col_map = [
                F("timestamp"),
                F("city__country__code"),
                F("city__name"),
                F("celltower__count"),
                F("temp"),
                F("voltage_raw"),
            ]
            device = None

            if data["imei"] == 0:
                response["data"] = []
                response["recordsFiltered"] = 0
                response["recordsTotal"] = 0
            else:
                try:
                    device = Device.objects.get(sn=int(data["imei"]))
                    if request.user not in device.users.all():
                        return HttpResponseForbidden()
                    status_query = Status.objects.filter(device=device).annotate(Count("celltower"))
                    if data["timespan"]["start"] != 0:
                        status_query = status_query.filter(
                            timestamp__gt=timezone.datetime.fromtimestamp(data["timespan"]["start"])
                        )
                    if data["timespan"]["end"] != 0:
                        status_query = status_query.filter(
                            timestamp__lt=timezone.datetime.fromtimestamp(data["timespan"]["end"])
                        )
                    if len(data["search"]["value"]) > 0:
                        status_query = status_query.filter(
                            Q(city__name__contains=data["search"]["value"])
                            | Q(city__country__code__contains=data["search"]["value"])
                            | Q(city__country__name__contains=data["search"]["value"])
                        )
                    status_query = (
                        status_query.all()
                        .order_by(*[col_map[o["column"]].__getattribute__(o["dir"])() for o in data["order"]])
                        .all()
                    )
                except Exception as e:
                    response["error"] = str(e)
                    status_query = Status.objects.none()

                paginator = Paginator(status_query, data["length"])
                response["data"] = [
                    {
                        "timestamp": {
                            "display": str(timezone.localtime(s.timestamp).strftime("%d.%m.%Y %H:%M:%S")),
                            "timestamp": int(s.timestamp.timestamp()),
                        },
                        "battery": {
                            "voltage": s.voltage,
                            "percentage": s.battery_percentage,
                            "display": "",
                        },
                        "lon": s.lon,
                        "lat": s.lat,
                        "id": s.id,
                        "radius": s.radius * 1000,
                        "city": s.city.name if s.city else "???",
                        "celltower": len(s.cleaned_measurements),
                        "country": s.country.code if s.country else "???",
                        "temp": s.temp if s.temp != -math.inf else "???",
                    }
                    for s in paginator.get_page(int(data["start"]) / paginator.per_page + 1)
                ]
                if request.session.get("debug"):
                    nextwake = device.next_update_expected()
                    response["data"].insert(
                        0,
                        {
                            "timestamp": {
                                "display": str(timezone.localtime(nextwake).strftime("%d.%m.%Y %H:%M:%S")),
                                "timestamp": int(nextwake.timestamp()),
                            },
                            "battery": {"voltage": 0, "percentage": 0, "display": "-"},
                            "lon": 0.0,
                            "lat": 0.0,
                            "id": 0,
                            "radius": 0,
                            "city": "...",
                            "celltower": "...",
                            "country": "...",
                            "temp": "...",
                        },
                    )
                response["recordsFiltered"] = paginator.count
                response["recordsTotal"] = Status.objects.filter(device=device).count() if data["imei"] != 0 else 0

        elif data["type"] == "tracker":
            col_map = ["sn", "alias", "last_position__voltage_raw"]
            try:
                devices = (
                    request.user.devices.filter(
                        Q(sn__contains=data["search"]["value"]) | Q(alias__contains=data["search"]["value"])
                    )
                    .all()
                    .order_by(*[F(col_map[o["column"]]).__getattribute__(o["dir"])() for o in data["order"]])
                )
            except Exception as e:
                devices = []
                response["error"] = str(e)
            paginator = Paginator(devices, int(data["length"]))
            response["data"] = [
                {
                    "imei": d.sn,
                    "alias": d.alias,
                    "battery": {
                        "percentage": d.battery_percentage,
                        "voltage": d.battery,
                        "display": "",
                    },
                }
                for d in paginator.get_page(int(data["start"]) / paginator.per_page + 1)
            ]

            response["recordsTotal"] = len(request.user.devices.all())

main/templates/main/_footer.html
{% comment %} <footer class="page-footer">
    <div class="container">
    <span class="text-muted">© 2021 Patrick Frontzek |</span>
    </div>
</footer> {% endcomment %}

main/templates/main/_messages.html
{% if messages %}
  <div id="messagesContainer">
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show text-center" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="far fa-times-circle"></i></span>
          </button>
        </div>
    {% endfor %}
</div>
{% endif %}

main/templates/main/_navbar.html
{% comment %} 
Copyright (C) 2021 Patrick Frontzek
This file is part of OpenAssetTracker-Server.

OpenAssetTracker-Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenAssetTracker-Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenAssetTracker-Server.  If not, see <http://www.gnu.org/licenses/>. 
{% endcomment %}

{% load static %}

<nav class="navbar justify-content-between shadow p-2 mb-0">
        <a href="/" class="navbar-brand bg-white rounded"{% if auth %} style="visibility: hidden;" {% endif %}><img src="{% static "main/img/logo_.png" %}" height="30" class="d-inline-block align-top"/></a>
                {% if request.user.is_authenticated %}
                    {% if debug %}
                        <a class="btn btn-danger" href="{% url "debug" %}">Debug</a>
                        {% endif %}
                <div class="btn-group">
                <button class="btn btn-primary" type="button">
                       {{ request.user.username }}
                </button>
                    <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileDropdown">
                    {% if request.user.is_staff %}
                        <a href="{% url "admincontrol" %}" class="dropdown-item">Verwaltung</a>
                        <a href="{% url "auth:create_user" %}" class="dropdown-item">Benutzer anlegen</a>
                        {% if debug %}<a href="/admin" class="dropdown-item">Admin</a>{% endif %}
                        <a href="{% url "debug" %}" class="dropdown-item">Debug</a>
<div class="dropdown-divider"></div>
                        {% endif %}
                    <a href="{% url "auth:logout" %}" class="dropdown-item">Logout</a>
                </div>
                </div>

                {% else %}
                <a href="{% url "auth:login" %}" class="btn btn-success">Login</a>
                {% endif %}
</nav>

main/templates/main/admin.html
{% comment %} 
Copyright (C) 2021 Patrick Frontzek
This file is part of OpenAssetTracker-Server.

OpenAssetTracker-Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenAssetTracker-Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenAssetTracker-Server.  If not, see <http://www.gnu.org/licenses/>. 
{% endcomment %}

{% extends "main/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-6 mb-3">
        <div class="card">
            <form method="post">
                {% csrf_token %}
                <div class="card-header text-center">
                    <span class="card-title">Benutzerverwaltung</span>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="userSelectUser">Benutzer</label>
                        <select id="userSelectUser" class="custom-select">
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="userSelectTracker">Tracker</label>
                        <select id="userSelectTracker" class="custom-select" multiple>
                        {% for device in devices %}
                            <option value="{{ device.sn }}">{{ device }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="userIsStaff" {% if request.user.is_staff %}checked{% endif %}>
                        <label class="custom-control-label" for="userIsStaff">Ist Mitarbeiter</label>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button class="btn btn-success ">Speichern</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-6 mb-3">
        <div class="card">
            <form method="post">
                {% csrf_token %}
                <div class="card-header text-center">
                    <span class="card-title">Trackerverwaltung</span>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="trackerSelectTracker">Tracker</label>
                        <select id="trackerSelectTracker" class="custom-select">
                        <option value="-1" selected>Neuer Tracker</option>
                            {% for device in devices %}
                                <option value="{{ device.sn }}">{{ device }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="trackerAlias">Alias</label>
                        <input type="text" class="form-control" id="trackerAlias" placeholder="Alias ...">
                    </div>
                    <div class="form-group">
                        <label for="trackerImei">IMEI</label>
                        <input type="number" class="form-control" id="trackerImei" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="trackerSelectUser">Benutzer</label>
                        <select id="trackerSelectUser" class="custom-select" multiple>
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="trackerSleeptime">Wartezeit</label>
                        <div class="input-group">
                            <input type="number" class="form-control" id="trackerSleeptime">
                            <div class="input-group-append">
                                <select class="custom-select" id="trackerSleeptimeUnit">
                                    {% for value, unit in sleeptimeUnits %}
                                        <option value="{{ value }}">{{ unit }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button class="btn btn-success ">Speichern</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-12">
        <div class="card">
            <form method="post">
                <div class="card-header text-center">
                    <span class="card-title">Benutzer anlegen</span>
                </div>
                <div class="card-body">
                        {% csrf_token %}
                        {% with WIDGET_ERROR_CLASS='is-invalid' %}
                            {% for field in usercreationform.visible_fields %}
                                <div class="form-group">
                                    <label for="{{ field.id }}">{{ field.label }}</label>
                                    {% render_field field class+="form-control" %}
                                    {% if field.errors %}
                                        <div class="invalid-feedback">{{ field.errors }}</div>
                                    {% endif %}
                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        {% endwith %}
                </div>
                <div class="card-footer text-right">
                    <button class="btn btn-outline-info ">Erstellen</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script>
trackerSelectTracker = $("#trackerSelectTracker");
trackerSelectUser = $("#trackerSelectUser");
trackerAlias = $("#trackerAlias");
trackerImei = $("#trackerImei");
trackerSleeptime = $("#trackerSleeptime");
trackerSleeptimeUnit = $("#trackerSleeptimeUnit");

trackerSelectTracker.change(() => {
    $.ajax({% url "trackerData_base" %} + trackerSelectTracker.val()).done((data) => {
        trackerAlias.val(data["alias"]);
        trackerImei.val(data["imei"]);
        trackerSleeptime.val(data["sleeptime"]);
        trackerSleeptimeUnit.val(data["sleeptime_unit"]);
        trackerSelectUser.val(data["users"]).attr("selected", true);
    });
});
</script>
{% endblock %}

main/templates/main/base.html
{% comment %} 
Copyright (C) 2021 Patrick Frontzek
This file is part of OpenAssetTracker-Server.

OpenAssetTracker-Server is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenAssetTracker-Server is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenAssetTracker-Server.  If not, see <http://www.gnu.org/licenses/>. 
{% endcomment %}

{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
<link rel="shortcut icon" type="image/png" href="{% static 'main/img/favicon.png' %}"/>
<link rel="manifest" href="{% url "webmanifest" %}">
<link href="{% static "fontawesome/css/all.css" %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet" media="screen">
    {% block head %}{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body class="">
{% include "main/_navbar.html" %}
<main class="container-fluid pl-0 pr-0 pt-0" style="overflow: hidden">
<div class="row">
<div class="col-sm-1 d-block"></div>
<div class="col-sm-10 content-col">
{% include "main/_messages.html" with messages=messages %}
    {% block content %}
    {% endblock %}
</div>
<div class="col-sm-1 d-block"></div>
</div>
</main>
{% block footer %}
{% endblock footer %}
<div id="modalContainer">
{% block modals %}{% endblock modals %}
</div>
{% include "main/_footer.html" %}
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block javascript %}{% endblock %}
</body>
</html>